#!/usr/bin/env node
/* Harvest the curated Pexels photos into a self-contained, bundled module.
 *
 * Reads the keyword→URL map from src/content/pximg.ts, downloads each photo at a small
 * cropped size, and writes src/content/photos.ts as base64 data: URIs. After this runs,
 * tphoto() (src/lib/photo.ts) serves stored photos — real images offline, in the artifact
 * preview, and CORS-clean for Export/Record — with zero runtime network calls.
 *
 * Run it anywhere that can reach images.pexels.com (a laptop, or a Vercel prebuild):
 *   node scripts/prefetch-photos.mjs
 * No API key needed — these are public CDN image URLs. Re-run to refresh.
 *
 * Safe to fail: on a network/policy block it writes an empty map and exits 0, so the build
 * never breaks — templates just fall back to remote URLs / gradients until it succeeds. */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dir = dirname(fileURLToPath(import.meta.url))
const SRC = resolve(__dir, '../src/content/pximg.ts')
const OUT = resolve(__dir, '../src/content/photos.ts')
const W = 480, H = 320            // display size — small, cropped, plenty for the mockups
const CONCURRENCY = 6

/** Pull the "keyword": "url" pairs out of the PXIMG object literal. */
async function readMap() {
  const txt = await readFile(SRC, 'utf8')
  const block = txt.slice(txt.indexOf('PXIMG'), txt.indexOf('KWSYN') > 0 ? txt.indexOf('KWSYN') : undefined)
  const out = {}
  const re = /"([a-z0-9]+)":\s*"([^"]+pexels[^"]+)"/g
  let m
  while ((m = re.exec(block))) out[m[1]] = m[2]
  return out
}

/** Force a small, cropped, compressed variant of a Pexels CDN URL. */
function small(url) {
  const base = url.split('?')[0]
  return `${base}?auto=compress&cs=tinysrgb&fit=crop&w=${W}&h=${H}`
}

async function grab(key, url) {
  try {
    const r = await fetch(small(url))
    if (!r.ok) throw new Error('HTTP ' + r.status)
    const buf = Buffer.from(await r.arrayBuffer())
    const mime = url.includes('.png') ? 'image/png' : 'image/jpeg'
    return `data:${mime};base64,${buf.toString('base64')}`
  } catch (e) {
    console.warn(`  skip ${key}: ${e.message}`)
    return null
  }
}

async function main() {
  const map = await readMap()
  const keys = Object.keys(map)
  console.log(`Prefetching ${keys.length} photos (${W}×${H})…`)
  const photos = {}
  for (let i = 0; i < keys.length; i += CONCURRENCY) {
    const batch = keys.slice(i, i + CONCURRENCY)
    const res = await Promise.all(batch.map((k) => grab(k, map[k])))
    batch.forEach((k, j) => { if (res[j]) photos[k] = res[j] })
    console.log(`  ${Math.min(i + CONCURRENCY, keys.length)}/${keys.length}`)
  }
  const n = Object.keys(photos).length
  const bytes = Object.values(photos).reduce((a, s) => a + s.length, 0)
  const header = `/* AUTO-GENERATED by scripts/prefetch-photos.mjs — do not edit by hand.\n * ${n}/${keys.length} curated Pexels photos, stored as data: URIs (~${(bytes / 1024 / 1024).toFixed(2)} MB).\n * tphoto() prefers these, so template photos work offline + in the preview with no network. */\n`
  const body = 'export const PHOTO: Record<string, string> = ' + JSON.stringify(photos, null, 0) + '\n'
  await mkdir(dirname(OUT), { recursive: true })
  await writeFile(OUT, header + body)
  console.log(`Wrote ${OUT} — ${n} photos, ~${(bytes / 1024 / 1024).toFixed(2)} MB.`)
  if (n === 0) console.log('(0 fetched — network/policy block? The app falls back to remote URLs / gradients.)')
}

main().catch((e) => { console.error(e); process.exit(0) })
